version: "3"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: tech-mancing-be
        ports:
            - "9001:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        networks:
            - tech-mancing-network

    mysql:
        image: mysql:latest
        container_name: mysql-tech-mancing
        environment:
            MYSQL_DATABASE: db_tech_mancing
            MYSQL_USER: user
            MYSQL_PASSWORD: Saynotodream64
            MYSQL_ROOT_PASSWORD: Saynotodream64
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - tech-mancing-network

networks:
    tech-mancing-network:
        driver: bridge

volumes:
    mysql-data:
