version: "3.8"

services:
  nginx:
    container_name: nginx-tech-mancing
    image: nginx:alpine
    ports:
      - "9001:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - mysql
    networks:
      - tech-mancing-network

  mysql:
    container_name: mysql-tech-mancing-db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Saynotodream64
      MYSQL_DATABASE: db_tech_mancing
      MYSQL_USER: saynotodream
      MYSQL_PASSWORD: Saynotodream64
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - tech-mancing-network

volumes:
  mysql-data:

networks:
  tech-mancing-network:
