version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "9001:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - tech-mancing-network

  php:
    image: php:latest
    volumes:
      - ./src:/var/www/html
    networks:
      - tech-mancing-network

  mysql:
    container_name: mysql-tech-mancing-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Saynotodream64
      MYSQL_DATABASE: db_tech_mancing
      MYSQL_USER: saynotodream
      MYSQL_PASSWORD: Saynotodream64
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - tech-mancing-network

volumes:
  mysql-data:

networks:
  tech-mancing-network:
