version: "3"

services:
    # Laravel Application
    app:
        image: laravel:latest # Use an official Laravel image or create your own Dockerfile
        container_name: tech-mancing-be
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./laravel:/var/www/html
        ports:
            - "3005:80" # Map port 3005 on the host to port 80 in the container
        environment:
            - APP_ENV=local
            - APP_KEY=your_app_key # Replace with your Laravel app key
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=db_tech_mancing
            - DB_USERNAME=root
            - DB_PASSWORD=0p3nw0rld

    # MySQL Database
    db:
        image: mysql:5.7
        container_name: db_tech_mancing
        restart: unless-stopped
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=db_tech_mancing
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=0p3nw0rld
        ports:
            - "3306:3306" # Map port 3306 on the host to port 3306 in the container
